kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: taskrun-with-failing-step-
spec:
  taskSpec:
    steps:
    # create a file with some content which needs to be verified in the following step
    # exit with a non-zero exit code after creating a file but configure this step to ignore step error
    - image: alpine
      name: failing-step
      exitCode: 0
      script: |
        # failing process
        echo -n 123 > /tekton/results/failing-step.txt
        exit 123
    # verify the file created in previous step exists, if not, exit with 1 which should make the test automation fail
    - image: alpine
      name: verify-file-exist
      script: |
        FILE=/tekton/results/failing-step.txt
        if [ -f "$FILE" ]; then
          echo "$FILE exists."
          echo "Yay! the file exists which was created in the previous step where the step error was ignored"
        else
          echo "$FILE does not exist."
          exit 1
        fi
