kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-pipelinerun-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
    - name: task1
      params:
      - name: pipeline-uid
        value: "$(context.pipelineRun.uid)"
      - name: pipeline-name
        value: "$(context.pipeline.name)"
      - name: pipelineRun-name
        value: "$(context.pipelineRun.name)"
      - name: pipelineRun-pipelineTasks
        value: "$(context.pipelineRun.pipelineTasks)"
      taskSpec:
        params:
        - name: pipeline-uid
        - name: pipeline-name
        - name: pipelineRun-name
        - name: pipelineRun-pipelineTasks
        steps:
        - image: ubuntu
          name: print-uid
          script: |
            echo "TaskRun UID: $(context.taskRun.uid)"
            echo "PipelineRun UID from params: $(params.pipeline-uid)"
        - image: ubuntu
          name: print-names
          script: |
            echo "Task name: $(context.task.name)"
            echo "TaskRun name: $(context.taskRun.name)"
            echo "Pipeline name from params: $(params.pipeline-name)"
            echo "PipelineRun name from params: $(params.pipelineRun-name)"
            echo "Pipeline Task names: $(params.pipelineRun-pipelineTasks)"
