apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: task-with-workspace-run-
spec:
  taskSpec:
    steps:
      - name: list-files
        image: ubuntu
        script: |
          #!/usr/bin/env bash
          echo $(workspaces.read-allowed.path)
          ls /hello/
          ls $(workspaces.read-allowed.path)/hello
          ls /workspace/hello
    workspaces:
      - name: read-allowed
        mountPath: /mypath/hello/
  workspaces:
    - name: read-allowed
      subPath: hello
      volumeClaimTemplate:
        metadata:
          name: pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
